{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import re\n",
    "from __future__ import absolute_import, unicode_literals\n",
    "#from .celery import app\n",
    "\n",
    "\n",
    "#@app.task\n",
    "def wordCount():\n",
    "\n",
    "    wantedWords = ['han', 'hon', 'hen', 'den', 'denna', 'denne']\n",
    "    #root = '/data/data/'\n",
    "    root = '/home/ubuntu/test/data/'\n",
    "    my_dict = {}\n",
    "    print('hjhh')\n",
    "    for file in getFiles(root):\n",
    "        with open(root + file) as f:\n",
    "            print(f)\n",
    "            for line in f:\n",
    "                if (len(line) > 0 and not line == '\\n'):\n",
    "                    line = line.strip() #Remove trailing and starting spaces\n",
    "                    \n",
    "                    parsedTweet = json.loads(line)\n",
    "\n",
    "\n",
    "                    if not (parsedTweet[\"retweeted\"]):\n",
    "\n",
    "\n",
    "                        words = cleanTweet(parsedTweet)\n",
    "\n",
    "                        for word in words:\n",
    "                            if word in wantedWords: \n",
    "                                my_dict[word] = my_dict.get(word, 0) + 1\n",
    "                                \n",
    "\n",
    "\n",
    "    return(my_dict)\n",
    "\n",
    "def cleanTweet(parsedString):\n",
    "    words = parsedString[\"text\"]\n",
    "    words = re.sub('[^a-zA-Z\\s]', '', words.lower()).split()\n",
    "    return words\n",
    "\n",
    "def getFiles(root):\n",
    "    print('getfiles')\n",
    "    for root, dirs, files in os.walk(root):\n",
    "        for file in files:\n",
    "            yield file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import absolute_import, unicode_literals\n",
    "from .celery import app\n",
    "\n",
    "@app.task\n",
    "def wordCount():\n",
    "    return x + y\n",
    "\n",
    "@app.task\n",
    "def mul(x, y):\n",
    "    return x * y\n",
    "\n",
    "@app.task\n",
    "def xsum(numbers):\n",
    "    return sum(numbers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def cleanTweet(parsedString):\n",
    "    words = parsedString[\"text\"]\n",
    "    words = re.sub('[^a-zA-Z\\s]', '', words.lower()).split()\n",
    "    return words\n",
    "\n",
    "def getFiles(root):\n",
    "    print('getfiles')\n",
    "    for root, dirs, files in os.walk(root):\n",
    "        for file in files:\n",
    "            yield file\n",
    "    "
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hjhh\n",
      "getfiles\n",
      "<open file u'/home/ubuntu/test/worker-2.log', mode 'r' at 0x7f6b28202c90>\n",
      "FAIL!\n",
      "[2018-10-10 14:44:26,723: WARNING/ForkPoolWorker-2] hjhh\n",
      "FAIL!\n",
      "[2018-10-10 14:44:26,724: WARNING/ForkPoolWorker-2] getfiles\n",
      "FAIL!\n",
      "[2018-10-10 14:44:26,724: WARNING/ForkPoolWorker-2] <open file u'/home/ubuntu/test/worker-2.log', mode 'r' at 0x7f268a02f6f0>\n",
      "FAIL!\n",
      "[2018-10-10 14:44:26,766: ERROR/ForkPoolWorker-2] Task code.tasks.wordCount[759295ee-0b7f-4801-aff3-2fe728e84de7] raised unexpected: ValueError('Expecting , delimiter: line 1 column 6 (char 5)',)\n",
      "FAIL!\n",
      "Traceback (most recent call last):\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 382, in trace_task\n",
      "FAIL!\n",
      "R = retval = fun(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 641, in __protected_call__\n",
      "FAIL!\n",
      "return self.run(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/test/code/tasks.py\", line 23, in wordCount\n",
      "FAIL!\n",
      "parsedTweet = json.loads(line)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "FAIL!\n",
      "return _default_decoder.decode(s)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "FAIL!\n",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "FAIL!\n",
      "obj, end = self.scan_once(s, idx)\n",
      "FAIL!\n",
      "ValueError: Expecting , delimiter: line 1 column 6 (char 5)\n",
      "FAIL!\n",
      "[2018-10-10 14:46:41,332: WARNING/ForkPoolWorker-2] hjhh\n",
      "FAIL!\n",
      "[2018-10-10 14:46:41,332: WARNING/ForkPoolWorker-2] getfiles\n",
      "FAIL!\n",
      "[2018-10-10 14:46:41,332: WARNING/ForkPoolWorker-2] <open file u'/home/ubuntu/test/worker-2.log', mode 'r' at 0x7f268a02f6f0>\n",
      "FAIL!\n",
      "[2018-10-10 14:46:41,334: ERROR/ForkPoolWorker-2] Task code.tasks.wordCount[07f6efdc-07e3-4f53-82fa-b0da9ee50059] raised unexpected: ValueError('Expecting , delimiter: line 1 column 6 (char 5)',)\n",
      "FAIL!\n",
      "Traceback (most recent call last):\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 382, in trace_task\n",
      "FAIL!\n",
      "R = retval = fun(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 641, in __protected_call__\n",
      "FAIL!\n",
      "return self.run(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/test/code/tasks.py\", line 23, in wordCount\n",
      "FAIL!\n",
      "parsedTweet = json.loads(line)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "FAIL!\n",
      "return _default_decoder.decode(s)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "FAIL!\n",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "FAIL!\n",
      "obj, end = self.scan_once(s, idx)\n",
      "FAIL!\n",
      "ValueError: Expecting , delimiter: line 1 column 6 (char 5)\n",
      "FAIL!\n",
      "[2018-10-10 14:53:27,071: WARNING/ForkPoolWorker-2] hjhh\n",
      "FAIL!\n",
      "[2018-10-10 14:53:27,071: WARNING/ForkPoolWorker-2] getfiles\n",
      "FAIL!\n",
      "[2018-10-10 14:53:27,072: WARNING/ForkPoolWorker-2] <open file u'/home/ubuntu/test/worker-2.log', mode 'r' at 0x7f268a02f6f0>\n",
      "FAIL!\n",
      "[2018-10-10 14:53:27,093: ERROR/ForkPoolWorker-2] Task code.tasks.wordCount[f9c6eb80-a652-4efb-ab2d-48c227265f40] raised unexpected: ValueError('Expecting , delimiter: line 1 column 6 (char 5)',)\n",
      "FAIL!\n",
      "Traceback (most recent call last):\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 382, in trace_task\n",
      "FAIL!\n",
      "R = retval = fun(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/app/trace.py\", line 641, in __protected_call__\n",
      "FAIL!\n",
      "return self.run(*args, **kwargs)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/test/code/tasks.py\", line 23, in wordCount\n",
      "FAIL!\n",
      "parsedTweet = json.loads(line)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "FAIL!\n",
      "return _default_decoder.decode(s)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "FAIL!\n",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "FAIL!\n",
      "obj, end = self.scan_once(s, idx)\n",
      "FAIL!\n",
      "ValueError: Expecting , delimiter: line 1 column 6 (char 5)\n",
      "<open file u'/home/ubuntu/test/worker-1.log', mode 'r' at 0x7f6b28202c00>\n",
      "<open file u'/home/ubuntu/test/05cb5036-2170-401b-947d-68f9191b21c6', mode 'r' at 0x7f6b28202c90>\n",
      "<open file u'/home/ubuntu/test/worker.pid', mode 'r' at 0x7f6b28202db0>\n",
      "FAIL!\n",
      "5343\n",
      "<open file u'/home/ubuntu/test/094b1612-1832-429e-98c1-ae06e56d88d6', mode 'r' at 0x7f6b28202ed0>\n",
      "<open file u'/home/ubuntu/test/worker.log', mode 'r' at 0x7f6b28202c90>\n",
      "FAIL!\n",
      "[2018-10-10 14:43:55,750: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//\n",
      "FAIL!\n",
      "[2018-10-10 14:43:55,776: INFO/MainProcess] mingle: searching for neighbors\n",
      "FAIL!\n",
      "[2018-10-10 14:43:56,814: INFO/MainProcess] mingle: all alone\n",
      "FAIL!\n",
      "[2018-10-10 14:43:56,836: INFO/MainProcess] worker@supersecretinstance ready.\n",
      "FAIL!\n",
      "[2018-10-10 14:44:26,722: INFO/MainProcess] Received task: code.tasks.wordCount[759295ee-0b7f-4801-aff3-2fe728e84de7]\n",
      "FAIL!\n",
      "[2018-10-10 14:46:41,331: INFO/MainProcess] Received task: code.tasks.wordCount[07f6efdc-07e3-4f53-82fa-b0da9ee50059]\n",
      "FAIL!\n",
      "[2018-10-10 14:52:53,716: INFO/MainProcess] sync with celery@supersecretinstance\n",
      "FAIL!\n",
      "[2018-10-10 14:52:53,717: ERROR/MainProcess] Control command error: error(104, 'Connection reset by peer')\n",
      "FAIL!\n",
      "Traceback (most recent call last):\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/celery/worker/pidbox.py\", line 46, in on_message\n",
      "FAIL!\n",
      "self.node.handle_message(body, message)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/pidbox.py\", line 129, in handle_message\n",
      "FAIL!\n",
      "return self.dispatch(**body)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/pidbox.py\", line 112, in dispatch\n",
      "FAIL!\n",
      "ticket=ticket)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/pidbox.py\", line 135, in reply\n",
      "FAIL!\n",
      "serializer=self.mailbox.serializer)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/pidbox.py\", line 265, in _publish_reply\n",
      "FAIL!\n",
      "**opts\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py\", line 181, in publish\n",
      "FAIL!\n",
      "exchange_name, declare,\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py\", line 194, in _publish\n",
      "FAIL!\n",
      "[maybe_declare(entity) for entity in declare]\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py\", line 102, in maybe_declare\n",
      "FAIL!\n",
      "return maybe_declare(entity, self.channel, retry, **retry_policy)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/common.py\", line 129, in maybe_declare\n",
      "FAIL!\n",
      "return _maybe_declare(entity, declared, ident, channel, orig)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/common.py\", line 135, in _maybe_declare\n",
      "FAIL!\n",
      "entity.declare(channel=channel)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/kombu/entity.py\", line 185, in declare\n",
      "FAIL!\n",
      "nowait=nowait, passive=passive,\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/amqp/channel.py\", line 614, in exchange_declare\n",
      "FAIL!\n",
      "wait=None if nowait else spec.Exchange.DeclareOk,\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/amqp/abstract_channel.py\", line 50, in send_method\n",
      "FAIL!\n",
      "conn.frame_writer(1, self.channel_id, sig, args, content)\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/amqp/method_framing.py\", line 166, in write_frame\n",
      "FAIL!\n",
      "write(view[:offset])\n",
      "FAIL!\n",
      "File \"/home/ubuntu/.local/lib/python2.7/site-packages/amqp/transport.py\", line 275, in write\n",
      "FAIL!\n",
      "self._write(s)\n",
      "FAIL!\n",
      "File \"/usr/lib/python2.7/socket.py\", line 228, in meth\n",
      "FAIL!\n",
      "return getattr(self._sock,name)(*args)\n",
      "FAIL!\n",
      "error: [Errno 104] Connection reset by peer\n",
      "FAIL!\n",
      "[2018-10-10 14:53:27,068: INFO/MainProcess] Received task: code.tasks.wordCount[f9c6eb80-a652-4efb-ab2d-48c227265f40]\n"
     ]
    },
    {
     "ename": "IOError",
     "evalue": "[Errno 2] No such file or directory: u'/home/ubuntu/test/__init__.py'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIOError\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-6ca5a98f787a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mres\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwordCount\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'hey'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mres\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-5-0467ac04f72f>\u001b[0m in \u001b[0;36mwordCount\u001b[0;34m()\u001b[0m\n\u001b[1;32m     15\u001b[0m     \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'hjhh'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     16\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mfile\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mgetFiles\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mroot\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 17\u001b[0;31m         \u001b[0;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mroot\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     18\u001b[0m             \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     19\u001b[0m             \u001b[0;32mfor\u001b[0m \u001b[0mline\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mIOError\u001b[0m: [Errno 2] No such file or directory: u'/home/ubuntu/test/__init__.py'"
     ]
    }
   ],
   "source": [
    "res = wordCount()\n",
    "print('hey')\n",
    "print(res)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
